apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-inven-collector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: github-inven-collector
  template:
    metadata:
      labels:
        app: github-inven-collector
    spec:
      containers:
        - name: github-inven-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50051