apiVersion: v1
kind: Service
metadata:
  name: github-inven-collector
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
  selector:
    app: github-inven-collector